### ISSUE TITLE
Error in custom_stream.tscn CodeTerrain.gd

### ISSUE THREAD

**Issue by pyramid3d** [tinmanjuggernaut/voxelgame#2]
I get the following error when running this demo scene (custom_stream.tscn) with Godot 3.2.4.rc:
```
CodeTerrain.gd:80
Invalid set index 'channel' (on base: 'null instance') with value of type 'int'.
terrain.stream.channel = VoxelBuffer.CHANNEL_SDF
```

**Comment by TokisanGames** [comment]
It's an issue with the newer version of voxel tools you are using, rather than Godot. It's saying that stream no longer has a property called channel. Zylann must have renamed it. 

What is the new property in stream that is used to specify whether to use the sdf or blocky channel? If you change that to the new property, you'll likely be able to continue with the new version.

**Comment by pyramid3d** [comment]
It seems there was some refactoring in the voxel tools code as most of the demo scenes are not working anymore. Is there any plan to update the demos in this repo, or is there still more refactoring to be expected?

**Comment by TokisanGames** [comment]
Yes, voxel tools has had many updates recently. I'm quite occupied at the moment and am not able to keep up to date with his changes.

Your options are either use these demos with the binaries linked in the Readme, or make the changes needed to link up to the new variable names and methods. For the former, the demos are just to show off functionality and features, not really as a basis for production code, so still serve that purpose. For the latter, it's likely only a few lines of code to adjust.

**Comment by pyramid3d** [comment]
Thanks or your feedback. That helps.
